vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        blog_images:
            uri_prefix: /uploads/blog/images
            upload_destination: '%kernel.project_dir%/public/uploads/blog/images'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        ville_images:
            uri_prefix: /uploads/images/ville
            upload_destination: '%kernel.project_dir%/public/uploads/images/ville'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true


